DROP PROCEDURE create_teaches;
DROP TRIGGER grade_excep_trigger on enrolls;
DROP FUNCTION grade_excep;
DROP VIEW better_students;
DROP TABLE requires;
DROP TABLE teaches;
DROP TABLE enrolls;
DROP TABLE course_offering;
DROP TABLE course;
DROP TABLE instructor;
DROP TABLE student;
DROP SEQUENCE seq_course;
DROP SEQUENCE seq_student;